abbr -a -- k "kubectl"
abbr -a -- kk "kubectl krew"
abbr -a -- vim "nvim"
abbr -a -- du "dust"
abbr -a -- find "fd"

# git stuff
abbr -a -- gco "git checkout"
abbr -a -- gcob "git checkout -b"
abbr -a -- gcom "git checkout main"
abbr -a -- gplo "git pull origin"
abbr -a -- gpsf "git push --force-with-lease"
abbr -a -- grpo "git remote prune origin"
abbr -a -- grbi "git rebase -i HEAD~"
abbr -a -- gbd "git branch -D"
